#Spring DataSource
server.port = 8082
spring.datasource.driverClassName=org.postgresql.Driver


broker.url = http://localhost:8084

spring.jpa.properties.hibernate.connection.isolation=TRANSACTION_SERIALIZABLE


spring.datasource.initialization-mode=always
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/onlybuns-v1
spring.datasource.username=postgres
spring.datasource.password=luka

#JPA-Hibernate
spring.jpa.show-sql = true

#kreira tabele na osnovu anotacija @Entity i kada aplikacija zavrsi sa radom dropuje ih
spring.jpa.hibernate.ddl-auto = create-drop

#https://stackoverflow.com/questions/43905119/postgres-error-method-org-postgresql-jdbc-pgconnection-createclob-is-not-imple
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#optimizacija za postgres upite
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL95Dialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=onlybuns.noreply@gmail.com
spring.mail.password=gqmtkaddlvugqqms
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.cache.jcache.config=classpath:ehcache.xml


#Prometheus postavke
management.metrics.export.prometheus.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator
management.endpoints.web.path-mapping.prometheus=prometheus
spring.security.user.name=admin
spring.security.user.password=admin
management.metrics.enable.process.cpu.usage=true
management.endpoint.health.show-details=always
management.endpoint.prometheus.sensitive=false
management.endpoints.web.exposure.include=*



#RateLimiter
# maksimalan broj poziva
resilience4j.ratelimiter.instances.comment.limitForPeriod=60

# u okviru vremenskog intervala
resilience4j.ratelimiter.instances.comment.limitRefreshPeriod=1h

# vreme cekanja na odgovor (recimo: u slucaju da je poziv stigao u 59 sekundi, a interval traje 60)
resilience4j.ratelimiter.instances.standard.timeoutDuration=0


#RabbitMQ queue
myqueue=agencija1
myqueue2=agencija2
myqueue3=agencija3
routingkey=spring-boot2
myexchange=myexchange
fanoutExchange=agenciesFanoutExchange